"""
Writes is_faq labels to the tickets table using the cached FAQ classification.
Prerequisites:
  - is_faq column must exist (ALTER TABLE tickets ADD COLUMN is_faq boolean DEFAULT false)
  - scripts/faq_cache.json must exist (already generated by count_faq.py)
"""
import json
import os
import sys
from dotenv import load_dotenv
from supabase import create_client

load_dotenv(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env"))

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

FAQ_CACHE_PATH = os.path.join(os.path.dirname(__file__), "faq_cache.json")
BATCH_SIZE = 100


def get_db():
    url = os.getenv("SUPABASE_URL")
    key = os.getenv("SUPABASE_SERVICE_KEY") or os.getenv("SUPABASE_KEY")
    if not url or not key:
        raise RuntimeError("SUPABASE_URL and SUPABASE_SERVICE_KEY must be set in .env")
    return create_client(url, key)


def fetch_all_tickets(db) -> list[dict]:
    tickets = []
    page_size = 1000
    offset = 0
    while True:
        rows = (
            db.table("tickets")
            .select("ticket_id,risk_score")
            .range(offset, offset + page_size - 1)
            .execute()
            .data
        )
        if not rows:
            break
        tickets.extend(rows)
        if len(rows) < page_size:
            break
        offset += page_size
    return tickets


def run():
    if not os.path.exists(FAQ_CACHE_PATH):
        print(f"ERROR: {FAQ_CACHE_PATH} not found. Run count_faq.py first.")
        sys.exit(1)

    with open(FAQ_CACHE_PATH, encoding="utf-8") as f:
        faq_map: dict[str, bool] = json.load(f)
    print(f"Cache loaded: {sum(v for v in faq_map.values())} FAQ / {len(faq_map)} classified")

    db = get_db()
    print("Fetching all tickets from Supabase...")
    all_tickets = fetch_all_tickets(db)
    print(f"Total tickets: {len(all_tickets)}")

    upserts = []
    for t in all_tickets:
        tid = t["ticket_id"]
        risk = t.get("risk_score") or 0
        # Tickets with risk_score >= 40 are never FAQ, regardless of cache
        is_faq = faq_map.get(tid, False) if risk < 40 else False
        upserts.append({"ticket_id": tid, "is_faq": is_faq})

    total_written = 0
    for i in range(0, len(upserts), BATCH_SIZE):
        batch = upserts[i:i + BATCH_SIZE]
        db.table("tickets").upsert(batch).execute()
        total_written += len(batch)
        if total_written % 1000 == 0 or total_written == len(upserts):
            print(f"  Written {total_written}/{len(upserts)} tickets...")

    faq_written = sum(1 for u in upserts if u["is_faq"])
    print(f"\nDone. {faq_written}/{len(upserts)} tickets marked as FAQ ({faq_written / len(upserts) * 100:.1f}%).")


if __name__ == "__main__":
    run()
